@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/RDF-QueryX-Lazy/project>
	deps:runtime-requirement         [ deps:on "Scalar::Util"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "common::sense"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "RDF::Query 2.900"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "parent"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

